---
title: "Immigrant_SupplementalAnalysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(lubridate)
library(readr)
library(janitor)
library(here)
library(haven)
library(modelsummary)
library(ggeffects)
library(margins)
library(scales)
library(nnet)
library(broom)
library(tigris)
library(sandwich)
library(lmtest)
```

```{r Step 0: data ingestion, include=TRUE}
cmps_merged <- read_csv(here("cmps_merged_civicorgdata_2024.csv"))
```

```{r Step 1: Re-run Models on Voter Turnout with Split Sample for Immigrants vs. U.S Born}
#Create Covariates
cmps_merged <- cmps_merged %>%
  mutate(trump_vote = ifelse(q17 == 1, 1, 0))

cmps_merged$gender_factor <- factor(cmps_merged$s14, 
                                   levels = 1:3,
                                   labels = c("Man", "Woman", "Non-binary"))

cmps_merged$income_factor <- factor(cmps_merged$hhinc, 
                                   levels = 1:5,
                                   labels = c("Less than $39k", "$40k-$59k", 
                                             "$60k-$99k", "$100k+", "Don't know"))

cmps_merged$income_ordinal <- ifelse(cmps_merged$s20 == 13, NA, cmps_merged$s20)

cmps_merged$education_factor <- factor(cmps_merged$s17, 
                                      levels = 1:7,
                                      labels = c("Grades 1-8", "Some high school", 
                                                "High school graduate or GED", "Some college",
                                                "Associates, 2-year degree", "Bachelors, 4-year degree",
                                                "Post-graduate degree"))

cmps_merged$age_factor <- factor(cmps_merged$agecat, 
                                levels = 1:5,
                                labels = c("16-17 yrs", "18-29 yrs", "30-44 yrs", 
                                          "45-64 yrs", "65+ yrs"))

# You might want to create age from birth year for easier interpretation
cmps_merged$agenum <- 2024 - cmps_merged$s2


cmps_merged$region_factor <- factor(cmps_merged$region, 
                                   levels = 1:4,
                                   labels = c("Midwest", "Northeast", "South", "West"))

cmps_merged$urban_factor <- factor(cmps_merged$s24, 
                                  levels = 1:5,
                                  labels = c("Large urban area", "Large suburb near large city",
                                            "Small suburb near small town or city", 
                                            "Small town or small city", "Rural area"))

cmps_merged$race_factor <- factor(cmps_merged$qraceid,
                                 levels = 1:6,
                                 labels = c("White",
                                           "Latino", 
                                           "Black",
                                           "Asian",
                                           "Native American",
                                           "MENA"))

cmps_merged_immigrant <- cmps_merged %>% 
  filter(s25 == 2)

cmps_merged_immigrantnonres <- cmps_merged %>%
  filter(s25 == 2 & s26 != 1)

model_trumpvote_immigrant_controlled <- glm(trump_vote ~ opc + gender_factor + income_factor + 
                        education_factor + age_factor + region_factor + urban_factor, 
                        data = cmps_merged_immigrant, 
                        family = binomial)

summary(model_trumpvote_immigrant_controlled)
```