---
title: "civiscoreanalysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(lubridate)
library(readr)
library(janitor)
library(here)
library(haven)
library(modelsummary)
library(ggeffects)
library(MASS)
library(margins)
library(scales)
library(nnet)
library(broom)
library(tigris)
```

```{r Step 0: data ingestion, include=TRUE}
cmps_merged <- read_csv(here("cmps_merged_civicorgdata.csv"))
```

```{r Step 1: Civic Engagement Regression Pt. 1, include=TRUE}
# First, let's explore the new civic infrastructure variable
cat("=== CIVIC INFRASTRUCTURE (OPC) VARIABLE EXPLORATION ===\n")
cat("Variable name: opc (opportunity for civic practices)\n")
cat("Variable type:", class(cmps_merged$opc), "\n")

# Basic descriptive statistics
summary(cmps_merged$opc)

cat("Missing values:", sum(is.na(cmps_merged$opc)), "\n")
cat("Unique values:", length(unique(cmps_merged$opc[!is.na(cmps_merged$opc)])), "\n")

# Distribution plot
hist(cmps_merged$opc, main = "Distribution of Civic Infrastructure (OPC)", 
     xlab = "Opportunity for Civic Practices", col = "lightblue", breaks = 30)

# Create other factor variables
cmps_merged$gender_factor <- factor(cmps_merged$s14, 
                                   levels = 1:3,
                                   labels = c("Man", "Woman", "Non-binary"))

cmps_merged$income_factor <- factor(cmps_merged$hhinc, 
                                   levels = 1:5,
                                   labels = c("Less than $39k", "$40k-$59k", 
                                             "$60k-$99k", "$100k+", "Don't know"))

cmps_merged$education_factor <- factor(cmps_merged$s17, 
                                      levels = 1:7,
                                      labels = c("Grades 1-8", "Some high school", 
                                                "High school graduate or GED", "Some college",
                                                "Associates, 2-year degree", "Bachelors, 4-year degree",
                                                "Post-graduate degree"))

cmps_merged$age_factor <- factor(cmps_merged$agecat, 
                                levels = 1:5,
                                labels = c("16-17 yrs", "18-29 yrs", "30-44 yrs", 
                                          "45-64 yrs", "65+ yrs"))

cmps_merged$region_factor <- factor(cmps_merged$region, 
                                   levels = 1:4,
                                   labels = c("Midwest", "Northeast", "South", "West"))

cmps_merged$urban_factor <- factor(cmps_merged$s24, 
                                  levels = 1:5,
                                  labels = c("Large urban area", "Large suburb near large city",
                                            "Small suburb near small town or city", 
                                            "Small town or small city", "Rural area"))

model1 <- lm(q56 ~ opc, data = cmps_merged)
summary(model1)
model1_full <- lm(q56 ~ opc + gender_factor + income_factor + education_factor + age_factor + region_factor + urban_factor, data = cmps_merged)
summary(model1_full)

cmps_merged_black <- cmps_merged %>%
  filter(s3r3 == 1)
model2 <- lm(q56 ~ opc, data = cmps_merged_black)
summary(model2)
model2_full <- lm(q56 ~ opc + gender_factor + income_factor + education_factor + age_factor + region_factor + urban_factor, data = cmps_merged_black)
summary(model2_full)

cmps_merged_white <- cmps_merged %>%
  filter(s3r1 == 1)
model3 <- lm(q56 ~ opc, data = cmps_merged_white)
summary(model3)
model3_full <- lm(q56 ~ opc + gender_factor + income_factor + education_factor + age_factor + region_factor + urban_factor, data = cmps_merged_white)
summary(model3_full)

cmps_merged_asian <- cmps_merged %>%
  filter(s3r4 == 1)
model4 <- lm(q56 ~ opc, data = cmps_merged_asian)
summary(model4)
model4_full <- lm(q56 ~ opc + gender_factor + income_factor + education_factor + age_factor + region_factor + urban_factor, data = cmps_merged_asian)
summary(model4_full)

cmps_merged_latino <- cmps_merged %>%
  filter(s3r2 == 1)
model5 <- lm(q56 ~ opc, data = cmps_merged_latino)
summary(model5)
model5_full <- lm(q56 ~ opc + gender_factor + income_factor + education_factor + age_factor + region_factor + urban_factor, data = cmps_merged_latino)
summary(model5_full)

```